#!/bin/bash

######################################
#   In crontab -e                    #
#   * * * * * /home/olaf/task_4.sh   #
######################################

t=4
while [ $t -gt 2 ];
do
echo "##################################################################"
echo "#  Select on or many of options:"
echo "#  1 .Number of CPU Cores"
echo "#  2 .Disk space"
echo "#  3 .Size of RAM"
echo "#  4 .Information about the last users logged on the host"
echo "#  5 .Calculate the number of active python/perl process"
echo "#  6 .Send all the info on email"
echo "#  CTRL+C to leave the program"
echo "#  Enter your option as eg. 134 to display options 1,3 and 4: "
echo "##################################################################"
var1=$(nproc | awk '{printf("Number of cores: %s\n", $1)}')
var2=$(df | awk '{ sum+=$2 } END {printf("Total diskspace: %skB\n", sum)}')
var3=$(grep MemTotal /proc/meminfo | awk '{printf("RAM memory: %skB\n", $2)}')
var4=$(echo -n "Last users: " && last | grep -v 'reboot' | head -n 2 | awk '{printf("%s \n", $1)}')
var5=$(ps aux | grep -e perl -e python | grep -v grep | wc -l | awk '{printf("Number of Perl/Python processes: %s\n", $1)}')

read l
for (( i=0; i<${#l}; i++ ));
do
letter="${l:$i:1}"
if [ $letter == "1" ]
then
echo $var1
elif [ $letter == "2" ]
then
echo $var2
elif [ $letter == "3" ]
then
echo $var3
elif [ $letter == "4" ]
then
echo $var4
elif [ $letter == "5" ]
then
echo $var5
elif [ $letter == "6" ]
then
echo "____________" > mmm.txt
echo $var1 >> mmm.txt
echo $var2 >> mmm.txt
echo $var4 >> mmm.txt
echo $var3 >> mmm.txt
echo $var5 >> mmm.txt && cat mmm.txt | ssmtp -vvv olaf.serafin305@gmail.com
fi
done
done
